### ISSUE TITLE
Change the number of columns

### ISSUE THREAD

**Issue by Giacint1** [pashashocky/obsidian-note-gallery#15] opened 2024-01-01 17:17 UTC
Is there any way I can change the number of columns from the default 4 to a different number, like 3 or 2?
I didn't find such an option in the available options or in the Styles file

**Comment by shiluanzzz** [comment] 2024-01-02 14:38
+1 feature request

**Comment by Denyerec** [comment] 2024-01-03 00:24
+1

**Comment by pashashocky** [comment] 2024-01-19 08:29
@Giacint1 @shiluanzzz @Denyerec back from holiday! Duplicate of #13, will get this in!

**Comment by pashashocky** [comment] 2024-02-05 23:25
This is now available in `0.0.57` :) Have fun, re-open if you have any issues, usage in the README.md :)

**Closed by pashashocky** 2024-02-05 23:25 UTC

**Comment by Denyerec** [comment] 2024-02-06 10:45
When trying the new columns feature it got stuck on "Indexing Database".
Even now removing the breakpoints config, it's still hung there, so unsure if this is related to the new code, or a separate issue.
